// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1fTNEHHJwGPd-ZbxDXRXcrU_ZUq-GuDE',
    appId: '1:952821458147:web:cbba0103797914200fd1d6',
    messagingSenderId: '952821458147',
    projectId: 'ecom-task-by-nikhil',
    authDomain: 'ecom-task-by-nikhil.firebaseapp.com',
    storageBucket: 'ecom-task-by-nikhil.appspot.com',
    measurementId: 'G-4Q3SZL496C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP6kz4LDbMKj13jiRTszXIMDgDJ2cR1lA',
    appId: '1:952821458147:android:1b20014047b628060fd1d6',
    messagingSenderId: '952821458147',
    projectId: 'ecom-task-by-nikhil',
    storageBucket: 'ecom-task-by-nikhil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtQY0Sh5x6WeS-yX_wI5xZq_Vwl-F8Dzk',
    appId: '1:952821458147:ios:fd931913742cccae0fd1d6',
    messagingSenderId: '952821458147',
    projectId: 'ecom-task-by-nikhil',
    storageBucket: 'ecom-task-by-nikhil.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtQY0Sh5x6WeS-yX_wI5xZq_Vwl-F8Dzk',
    appId: '1:952821458147:ios:da6b7f55c852645c0fd1d6',
    messagingSenderId: '952821458147',
    projectId: 'ecom-task-by-nikhil',
    storageBucket: 'ecom-task-by-nikhil.appspot.com',
    iosBundleId: 'com.example.ecom.RunnerTests',
  );
}
